### ISSUE TITLE
Make YT streams auto-start if streaming client comes online during a public opening

### ISSUE THREAD

**Issue by Tina-otoge** [LAP-Arcade/lapadmin#3]
Instead of having to manually start streams, during public openings, automatically create stream schedules for each game, and auto-start them as soon as it comes online.

If a stream comes offline and we are not ~30 min close to the closing time, create a new stream immediately and auto-start it again.

**Comment by Tina-otoge** [comment]
Add an helper module in `app/streams.py`

This module should consume static data in `/data/` for:
- Stream details (name, associated playlists, description, ...), make use of Python templating to not copy the same description for each game with only the name changing, do something like:
  ```yaml
  streams:
    entries:
      - game: beatmania IIDX 31 EPOLIS
        playlist: xxxx
      - game: SOUND VOLTEX EXCEED GEAR
        playlist: xxx
    title: "{game} @ LAP Paris"
    description: "blablabla Retrouvez ici en direct la borne {game} pendant chaque ouverture."
  ```
  And when constructing your data model, for example a Pydantic "GameStream" object defined in app/streams.py, compute the description at runtime using `self.description = data.streams.description.format(**data.streams.entries[x])`, see also the [Template class in the string standard module](https://docs.python.org/3/library/string.html#string.Template) if raw calls to `str.format` are too much of a challenge here.

A method in the app/streams.py that creates the stream entries on the LAP channel if (current time) - (next closing time) >= 30 min. This method could be called manually from an helper in app/cli/ and a task should be defined in app/tasks/ to call it periodically, see [msn-web/app/](https://github.com/asso-msn/msn-web/tree/develop/app) cli and tasks folders for examples

A route in app/routes/ or a CLI command in app/cli/ should generate a "multistream" web page by grouping all active livestreams found on the LAP_Arcade channel. Whether or not to only show streams that are found in playlists in `data.streams.entries[*].playlist` can be considered, but not necessary. Showing the YouTube Chat iframe is necessary, otherwise this would be a downgrade from our experience using multistream.me.
